services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meduzzen-back
    ports:
      - '${DEV_PORT}:${DEV_PORT}'
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    container_name: postgres
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata: